"""Generate deterministic pre-audit file and data-field inventories.

`docs/audits/pre_audit_file_inventory.csv` and
`docs/provenance/data_field_ledger.csv` were originally fully generated by
this script from the fixed pre-audit checkpoint commit and `data/*.csv`.
Both have since been maintained by hand beyond what this script's logic
produces: `data_field_ledger.csv` carries an eight-column schema with rows
for M01-M05 and empirical-load Phase 1 fields this script does not know
about (this script still only writes its original seven-column, `data/*.csv`
-only schema). `docs/audits/inventory_generation_manifest.json` carries a
hand-maintained `post_generation_updates` narrative field this script does
not write at all.

Regenerating any of these three files unconditionally would silently
overwrite that hand-maintained content with this script's narrower,
checkpoint-era output. `main()` refuses instead: it computes every candidate
output in memory first -- including the manifest, which needs only the other
two candidates' in-memory bytes, not an on-disk read -- and, before writing
anything, refuses if a target file already exists with content this script
would not reproduce exactly. The two CSVs are compared byte-for-byte; the
manifest is compared field-for-field, including nested content, against
everything except `MANIFEST_VOLATILE_KEYS` (currently only `timestamp`,
which legitimately differs on every rerun). See
`docs/provenance/generate_audit_inventory_ownership.md` for the governance
record. Realigning this script's own generation logic to the current
maintained schemas is a separate, larger task; this script does not attempt
that merge.
"""

from __future__ import annotations

import csv
import hashlib
import io
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHECKPOINT = "pre_audit_agent_derived_prototype"
COMMIT = "6485b3d2f4c9fb48e2349f548ba7c79c8821947d"

INVENTORY_PATH = ROOT / "docs/audits/pre_audit_file_inventory.csv"
FIELD_LEDGER_PATH = ROOT / "docs/provenance/data_field_ledger.csv"
MANIFEST_PATH = ROOT / "docs/audits/inventory_generation_manifest.json"

# The exact top-level keys this script's own manifest write produces. Any
# existing manifest with additional keys carries hand-maintained content
# (for example `post_generation_updates`) this script cannot reproduce.
MANIFEST_SCHEMA_KEYS = frozenset(
    {
        "checkpoint_commit",
        "checkpoint_tag",
        "command",
        "environment",
        "generating_script",
        "generating_script_sha256",
        "inputs",
        "outputs",
        "timestamp",
    }
)

# Keys expected to legitimately differ between two otherwise-identical
# generations (for example, a rerun on the same environment produces a new
# `timestamp`). Every other schema key, including nested content such as
# `outputs` or `environment`, must match exactly or the write is refused.
MANIFEST_VOLATILE_KEYS = frozenset({"timestamp"})


def git(*args: str) -> bytes:
    return subprocess.check_output(["git", *args], cwd=ROOT)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def kind(path: str) -> str:
    suffix = Path(path).suffix.lower()
    if suffix == ".py":
        return "python script"
    if suffix == ".ipynb":
        return "notebook with stored outputs"
    if suffix == ".csv":
        return "CSV data"
    if suffix == ".grtload":
        return "GRT XML model input"
    if suffix in {".png", ".jpg", ".jpeg"}:
        return "image/plot"
    if suffix == ".md":
        return "documentation"
    return "project file"


def artifact_status(path: str) -> str:
    if path.startswith("plots/") or path in {
        "data/ExpansionRatio.csv",
        "data/Predictions.csv",
        "data/calculated_metrics.csv",
        "data/cartridge_data_from_grt.csv",
        "data/demo_summary.txt",
        "data/derived_metrics.csv",
        "data/propellant_params.csv",
    }:
        return "generated or derived; manifest absent at checkpoint"
    if path == "data/CartridgeData.csv":
        return "input compilation; row/field provenance absent"
    return "source or project artifact"


def build_inventory_csv() -> bytes:
    rows = []
    for path in git("ls-tree", "-r", "--name-only", COMMIT).decode().splitlines():
        data = git("show", f"{COMMIT}:{path}")
        rows.append((path, kind(path), len(data), sha256(data), artifact_status(path), COMMIT))
    buffer = io.StringIO(newline="")
    writer = csv.writer(buffer)
    writer.writerow(["path", "file_type", "bytes", "sha256", "audit_status", "checkpoint_commit"])
    writer.writerows(rows)
    return buffer.getvalue().encode("utf-8")


UNITS = {
    "groove_dia": "in",
    "case_vol": "gr H2O",
    "case_length": "in",
    "cartridge_oal": "in",
    "oal": "in (generated parser output)",
    "barrel_length": "in",
    "eff_case_vol": "claimed gr H2O; source dependent",
    "bullet_dia": "in",
    "bullet_mass": "gr",
    "bullet_length": "in",
    "bulk_density": "mixed/ambiguous across artifacts",
    "propellant_Qex": "claimed kJ/kg",
    "propellant_mass": "gr",
    "load_ratio": "percent (apparent; unverified)",
    "eff_barrel_length": "in",
    "muzzle_vel": "ft/s",
    "est_pmax": "psi (claimed; method unknown)",
    "est_muzzle_pressure": "psi (claimed; method unknown)",
    "bore_area": "in2",
    "ER": "dimensionless; total-expansion convention",
    "predicted_charge": "gr",
    "efficiency_proxy": "ft/s per psi",
    "mass_ratio": "dimensionless",
    "Ba": "unknown; XML unit blank",
    "a0": "unknown; XML unit blank",
    "z1": "unknown; XML unit blank",
    "z2": "unknown; XML unit blank",
    "Ba_eff": "unknown experimental scalar",
}


def origin_for(path: Path, field: str) -> tuple[str, str, str]:
    name = path.name
    if name == "cartridge_data_from_grt.csv":
        if field == "eff_case_vol":
            return ("agent-generated assumption", "SRC-GRT-LOAD-001", "invalid Aeff area-to-volume mapping")
        return ("GRT-derived parameter or behavior", "SRC-GRT-LOAD-001", "generated by legacy parser")
    if name == "propellant_params.csv":
        if field == "Ba_eff":
            return ("ModernPowley experimental hypothesis", "", "unsupported derived scalar")
        return ("GRT-derived parameter or behavior", "SRC-GRT-LOAD-001", "one local GRT artifact")
    if name in {"Predictions.csv", "calculated_metrics.csv", "derived_metrics.csv", "ExpansionRatio.csv"}:
        return ("Derived quantity", "", "generator identified; upstream provenance incomplete")
    if name == "CartridgeData.csv":
        return ("Unknown or unresolved", "", "no row-level or field-level source record")
    return ("Unknown or unresolved", "", "generated artifact with incomplete provenance")


def build_field_ledger_csv() -> bytes:
    rows = []
    for path in sorted((ROOT / "data").glob("*.csv")):
        with path.open(newline="", encoding="utf-8") as handle:
            reader = csv.reader(handle)
            header = next(reader)
        for field in header:
            attribution, source_id, evidence = origin_for(path, field)
            status = "excluded from authoritative calculations" if attribution in {
                "Unknown or unresolved", "Agent-generated assumption", "ModernPowley experimental hypothesis"
            } else "descriptive/transcription use only"
            rows.append(
                (
                    str(path.relative_to(ROOT)), field, attribution, UNITS.get(field, "unknown or encoded in heading"),
                    source_id, evidence, status,
                )
            )
    buffer = io.StringIO(newline="")
    writer = csv.writer(buffer)
    writer.writerow(["data_asset", "field", "attribution_class", "unit", "source_id", "verification_evidence", "status"])
    writer.writerows(rows)
    return buffer.getvalue().encode("utf-8")


def build_manifest(inventory_bytes: bytes, field_ledger_bytes: bytes) -> dict:
    script_hash = sha256(Path(__file__).read_bytes())
    return {
        "checkpoint_commit": COMMIT,
        "checkpoint_tag": CHECKPOINT,
        "command": "uv run python scripts/generate_audit_inventory.py",
        "environment": {"python": sys.version.split()[0], "runner": "uv"},
        "generating_script": "scripts/generate_audit_inventory.py",
        "generating_script_sha256": script_hash,
        "inputs": [{"git_commit": COMMIT}, {"glob": "data/*.csv (current audited worktree)"}],
        "outputs": [
            {"path": "docs/audits/pre_audit_file_inventory.csv", "sha256": sha256(inventory_bytes)},
            {"path": "docs/provenance/data_field_ledger.csv", "sha256": sha256(field_ledger_bytes)},
        ],
        "timestamp": datetime.now().astimezone().isoformat(timespec="seconds"),
    }


def _display(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def csv_overwrite_conflict(path: Path, candidate: bytes) -> str | None:
    """Return a refusal reason if writing `candidate` to `path` would silently
    discard existing content this script did not produce, else None."""
    if not path.exists():
        return None
    existing = path.read_bytes()
    if existing == candidate:
        return None
    return (
        f"{_display(path)} already exists and differs from what this "
        "script would generate. This file has been hand-maintained beyond "
        "this script's original checkpoint-era logic; regenerating it would "
        "silently discard that content. Refusing to write."
    )


def manifest_overwrite_conflict(path: Path, candidate: dict) -> str | None:
    """Return a refusal reason if writing `candidate` to `path` would
    silently discard or change existing manifest content this script did not
    produce, else None. Compares full content (including nested values), not
    just top-level key presence; `MANIFEST_VOLATILE_KEYS` are excluded from
    the value comparison since they are expected to differ on every
    legitimate rerun."""
    if not path.exists():
        return None
    try:
        existing = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return f"{_display(path)} exists and is not valid JSON. Refusing to write."
    extra_keys = sorted(set(existing) - MANIFEST_SCHEMA_KEYS)
    if extra_keys:
        return (
            f"{_display(path)} already carries hand-maintained field(s) "
            f"{extra_keys} that are not part of this script's own manifest "
            "schema; regenerating it would silently delete them. Refusing to "
            "write."
        )
    existing_stable = {k: v for k, v in existing.items() if k not in MANIFEST_VOLATILE_KEYS}
    candidate_stable = {k: v for k, v in candidate.items() if k not in MANIFEST_VOLATILE_KEYS}
    if existing_stable != candidate_stable:
        changed = sorted(
            key
            for key in set(existing_stable) | set(candidate_stable)
            if existing_stable.get(key) != candidate_stable.get(key)
        )
        return (
            f"{_display(path)} already exists and differs from what this "
            f"script would generate in field(s) {changed} (ignoring only the "
            f"volatile field(s) {sorted(MANIFEST_VOLATILE_KEYS)}). Refusing "
            "to write."
        )
    return None


def main() -> None:
    # Every candidate output is built in memory before anything is written,
    # including the manifest -- it needs no on-disk CSV, only the in-memory
    # bytes' hashes -- so a refusal, or any unexpected failure while building
    # a candidate, can never leave the three outputs partially written.
    inventory_bytes = build_inventory_csv()
    field_ledger_bytes = build_field_ledger_csv()
    manifest = build_manifest(inventory_bytes, field_ledger_bytes)

    conflicts = [
        message
        for message in (
            csv_overwrite_conflict(INVENTORY_PATH, inventory_bytes),
            csv_overwrite_conflict(FIELD_LEDGER_PATH, field_ledger_bytes),
            manifest_overwrite_conflict(MANIFEST_PATH, manifest),
        )
        if message is not None
    ]
    if conflicts:
        sys.exit(
            "generate_audit_inventory.py refused to write (no output was "
            "modified):\n- " + "\n- ".join(conflicts)
        )

    INVENTORY_PATH.parent.mkdir(parents=True, exist_ok=True)
    INVENTORY_PATH.write_bytes(inventory_bytes)
    FIELD_LEDGER_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIELD_LEDGER_PATH.write_bytes(field_ledger_bytes)
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
