"""Generate deterministic pre-audit file and data-field inventories."""

from __future__ import annotations

import csv
from datetime import datetime
import hashlib
import json
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
CHECKPOINT = "pre_audit_agent_derived_prototype"
COMMIT = "6485b3d2f4c9fb48e2349f548ba7c79c8821947d"


def git(*args: str) -> bytes:
    return subprocess.check_output(["git", *args], cwd=ROOT)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def kind(path: str) -> str:
    suffix = Path(path).suffix.lower()
    if suffix == ".py":
        return "python script"
    if suffix == ".ipynb":
        return "notebook with stored outputs"
    if suffix == ".csv":
        return "CSV data"
    if suffix == ".grtload":
        return "GRT XML model input"
    if suffix in {".png", ".jpg", ".jpeg"}:
        return "image/plot"
    if suffix == ".md":
        return "documentation"
    return "project file"


def artifact_status(path: str) -> str:
    if path.startswith("plots/") or path in {
        "data/ExpansionRatio.csv",
        "data/Predictions.csv",
        "data/calculated_metrics.csv",
        "data/cartridge_data_from_grt.csv",
        "data/demo_summary.txt",
        "data/derived_metrics.csv",
        "data/propellant_params.csv",
    }:
        return "generated or derived; manifest absent at checkpoint"
    if path == "data/CartridgeData.csv":
        return "input compilation; row/field provenance absent"
    return "source or project artifact"


def write_inventory() -> Path:
    output = ROOT / "docs/audits/pre_audit_file_inventory.csv"
    output.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for path in git("ls-tree", "-r", "--name-only", COMMIT).decode().splitlines():
        data = git("show", f"{COMMIT}:{path}")
        rows.append((path, kind(path), len(data), sha256(data), artifact_status(path), COMMIT))
    with output.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["path", "file_type", "bytes", "sha256", "audit_status", "checkpoint_commit"])
        writer.writerows(rows)
    return output


UNITS = {
    "groove_dia": "in",
    "case_vol": "gr H2O",
    "case_length": "in",
    "cartridge_oal": "in",
    "oal": "in (generated parser output)",
    "barrel_length": "in",
    "eff_case_vol": "claimed gr H2O; source dependent",
    "bullet_dia": "in",
    "bullet_mass": "gr",
    "bullet_length": "in",
    "bulk_density": "mixed/ambiguous across artifacts",
    "propellant_Qex": "claimed kJ/kg",
    "propellant_mass": "gr",
    "load_ratio": "percent (apparent; unverified)",
    "eff_barrel_length": "in",
    "muzzle_vel": "ft/s",
    "est_pmax": "psi (claimed; method unknown)",
    "est_muzzle_pressure": "psi (claimed; method unknown)",
    "bore_area": "in2",
    "ER": "dimensionless; total-expansion convention",
    "predicted_charge": "gr",
    "efficiency_proxy": "ft/s per psi",
    "mass_ratio": "dimensionless",
    "Ba": "unknown; XML unit blank",
    "a0": "unknown; XML unit blank",
    "z1": "unknown; XML unit blank",
    "z2": "unknown; XML unit blank",
    "Ba_eff": "unknown experimental scalar",
}


def origin_for(path: Path, field: str) -> tuple[str, str, str]:
    name = path.name
    if name == "cartridge_data_from_grt.csv":
        if field == "eff_case_vol":
            return ("agent-generated assumption", "SRC-GRT-LOAD-001", "invalid Aeff area-to-volume mapping")
        return ("GRT-derived parameter or behavior", "SRC-GRT-LOAD-001", "generated by legacy parser")
    if name == "propellant_params.csv":
        if field == "Ba_eff":
            return ("ModernPowley experimental hypothesis", "", "unsupported derived scalar")
        return ("GRT-derived parameter or behavior", "SRC-GRT-LOAD-001", "one local GRT artifact")
    if name in {"Predictions.csv", "calculated_metrics.csv", "derived_metrics.csv", "ExpansionRatio.csv"}:
        return ("Derived quantity", "", "generator identified; upstream provenance incomplete")
    if name == "CartridgeData.csv":
        return ("Unknown or unresolved", "", "no row-level or field-level source record")
    return ("Unknown or unresolved", "", "generated artifact with incomplete provenance")


def write_field_ledger() -> Path:
    output = ROOT / "docs/provenance/data_field_ledger.csv"
    output.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for path in sorted((ROOT / "data").glob("*.csv")):
        with path.open(newline="", encoding="utf-8") as handle:
            reader = csv.reader(handle)
            header = next(reader)
        for field in header:
            attribution, source_id, evidence = origin_for(path, field)
            status = "excluded from authoritative calculations" if attribution in {
                "Unknown or unresolved", "Agent-generated assumption", "ModernPowley experimental hypothesis"
            } else "descriptive/transcription use only"
            rows.append(
                (
                    str(path.relative_to(ROOT)), field, attribution, UNITS.get(field, "unknown or encoded in heading"),
                    source_id, evidence, status,
                )
            )
    with output.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["data_asset", "field", "attribution_class", "unit", "source_id", "verification_evidence", "status"])
        writer.writerows(rows)
    return output


def main() -> None:
    outputs = [write_inventory(), write_field_ledger()]
    script_hash = sha256(Path(__file__).read_bytes())
    manifest = {
        "checkpoint_commit": COMMIT,
        "checkpoint_tag": CHECKPOINT,
        "command": "uv run python scripts/generate_audit_inventory.py",
        "environment": {"python": sys.version.split()[0], "runner": "uv"},
        "generating_script": "scripts/generate_audit_inventory.py",
        "generating_script_sha256": script_hash,
        "inputs": [{"git_commit": COMMIT}, {"glob": "data/*.csv (current audited worktree)"}],
        "outputs": [
            {"path": str(path.relative_to(ROOT)), "sha256": sha256(path.read_bytes())} for path in outputs
        ],
        "timestamp": datetime.now().astimezone().isoformat(timespec="seconds"),
    }
    manifest_path = ROOT / "docs/audits/inventory_generation_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
